"""
Google Play Store category constants.
Tuple format: (api_id, display_name)
api_id matches what apkeep / gpapi accept as category filters.
"""

CATEGORIES: list[tuple[str, str]] = [
    # Games
    ("GAME_ACTION",         "Games: Action"),
    ("GAME_ADVENTURE",      "Games: Adventure"),
    ("GAME_ARCADE",         "Games: Arcade"),
    ("GAME_BOARD",          "Games: Board"),
    ("GAME_CARD",           "Games: Card"),
    ("GAME_CASINO",         "Games: Casino"),
    ("GAME_CASUAL",         "Games: Casual"),
    ("GAME_EDUCATIONAL",    "Games: Educational"),
    ("GAME_MUSIC",          "Games: Music"),
    ("GAME_PUZZLE",         "Games: Puzzle"),
    ("GAME_RACING",         "Games: Racing"),
    ("GAME_ROLE_PLAYING",   "Games: Role Playing"),
    ("GAME_SIMULATION",     "Games: Simulation"),
    ("GAME_SPORTS",         "Games: Sports"),
    ("GAME_STRATEGY",       "Games: Strategy"),
    ("GAME_TRIVIA",         "Games: Trivia"),
    ("GAME_WORD",           "Games: Word"),
    # Apps
    ("ART_AND_DESIGN",      "Art & Design"),
    ("AUTO_AND_VEHICLES",   "Auto & Vehicles"),
    ("BEAUTY",              "Beauty"),
    ("BOOKS_AND_REFERENCE", "Books & Reference"),
    ("BUSINESS",            "Business"),
    ("COMICS",              "Comics"),
    ("COMMUNICATION",       "Communication"),
    ("DATING",              "Dating"),
    ("EDUCATION",           "Education"),
    ("ENTERTAINMENT",       "Entertainment"),
    ("EVENTS",              "Events"),
    ("FINANCE",             "Finance"),
    ("FOOD_AND_DRINK",      "Food & Drink"),
    ("HEALTH_AND_FITNESS",  "Health & Fitness"),
    ("HOUSE_AND_HOME",      "House & Home"),
    ("LIBRARIES_AND_DEMO",  "Libraries & Demo"),
    ("LIFESTYLE",           "Lifestyle"),
    ("MAPS_AND_NAVIGATION", "Maps & Navigation"),
    ("MEDICAL",             "Medical"),
    ("MUSIC_AND_AUDIO",     "Music & Audio"),
    ("NEWS_AND_MAGAZINES",  "News & Magazines"),
    ("PARENTING",           "Parenting"),
    ("PERSONALIZATION",     "Personalization"),
    ("PHOTOGRAPHY",         "Photography"),
    ("PRODUCTIVITY",        "Productivity"),
    ("SHOPPING",            "Shopping"),
    ("SOCIAL",              "Social"),
    ("SPORTS",              "Sports"),
    ("TOOLS",               "Tools"),
    ("TRAVEL_AND_LOCAL",    "Travel & Local"),
    ("VIDEO_PLAYERS",       "Video Players"),
    ("WEATHER",             "Weather"),
]
